### ISSUE TITLE
Meteor 1.8.1 cannot work

### ISSUE THREAD

**Issue by SvenWangChina** [nathantreid/meteor-vue-typescript-babel#1]
Meteor.js  1.8.1
Vue.js  2.6.10

app.vue：
`\<template>
    \<div class="app">
        Test Vue TypeScript
    \</div>
\</template>

<style scoped lang="less" src="index.less">
</style>

<script lang="ts">
    let message: string;

    export default {
        mounted() {
            message = 'world';
            console.log(`Hello, ${message}!`);
        }
    }
</script>`

I get follow issue when meteor run:
[vue-component] Error while compiling in tag <script> using lang ts Cannot read property 'unshift' of undefined
TypeError: Cannot read property 'unshift' of undefined
    at TypeScriptCompiler.inferExtraBabelOptions (packages/vue-component-typescript-babel/compiler.js:12:26)
    at TypeScriptCompiler.BCp.processOneFileForTarget (packages/babel-compiler.js:196:10)
    at typescriptHandler (packages/vue-component-typescript-babel/vue-typescript.js:19:29)
    at packages/meteor.js:306:21
    at VueComponentTagHandler.getResults (packages/vue-component/plugin/tag-handler.js:91:26)
    at compileTags (packages/vue-component/plugin/vue-compiler.js:532:18)
    at compileOneFileWithContents (packages/vue-component/plugin/vue-compiler.js:541:12)
    at VueCompo.compileOneFile (packages/vue-component/plugin/vue-compiler.js:140:12)
    at async.eachLimit (packages/vue-component/plugin/vue-compiler.js:57:34)
    at /Users/sven/.meteor/packages/akryum_vue-component/.0.15.1.1akbbmb.2cfr++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3110:16
    at replenish (/Users/sven/.meteor/packages/akryum_vue-component/.0.15.1.1akbbmb.2cfr++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:1011:17)
    at /Users/sven/.meteor/packages/akryum_vue-component/.0.15.1.1akbbmb.2cfr++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:1016:9
    at Object.eachLimit$1 (/Users/sven/.meteor/packages/akryum_vue-component/.0.15.1.1akbbmb.2cfr++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3196:24)
    at VueCompo.processFilesForTarget (packages/vue-component/plugin/vue-compiler.js:41:11)
    at __bottom_mark__ (/tools/utils/parse-stack.js:69:14)
    at /tools/isobuild/compiler-plugin.js:198:27
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at Profile.time (/tools/isobuild/compiler-plugin.js:185:22)
    at Function.time (/tools/tool-env/profile.js:305:10)
    at /tools/isobuild/compiler-plugin.js:184:15
    at Function._.each._.forEach (/Users/sven/.meteor/packages/meteor-tool/.1.8.1.4gwv5w.33478++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at CompilerPluginProcessor.runCompilerPlugins (/tools/isobuild/compiler-plugin.js:174:7)
    at ClientTarget._runCompilerPlugins (/tools/isobuild/bundler.js:1117:22)
    at buildmessage.enterJob (/tools/isobuild/bundler.js:849:34)
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at ClientTarget.make (/tools/isobuild/bundler.js:843:18)
    at /tools/isobuild/bundler.js:3175:14
    at webArchs.forEach.arch (/tools/isobuild/bundler.js:3326:25)
    at Array.forEach (<anonymous>)
    at /tools/isobuild/bundler.js:3280:14
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at bundle (/tools/isobuild/bundler.js:3156:31)
    at files.withCache (/tools/isobuild/bundler.js:3101:32)
    at Object.withCache (/tools/fs/files.js:1744:12)
    at Object.bundle (/tools/isobuild/bundler.js:3101:16)
    at Profile.run (/tools/runners/run-app.js:572:24)
    at Function.run (/tools/tool-env/profile.js:490:12)
    at bundleApp (/tools/runners/run-app.js:571:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:613:35)
    at AppRunner._fiber (/tools/runners/run-app.js:922:28)
    at /tools/runners/run-app.js:401:12

Can you share an example for Meteor 1.8.1 + Vue.js 2.6.10?Thanks very much.

**Comment by akanix42** [comment]
Thanks for the report. I just released v1.0.3 to fix this bug, which occurs when you don't have a `.babelrc` with a `plugins` section.
